language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
install: 
  - pip install -r requirements.txt
  - python setup.py -q install
script: nosetests -vv --attr=unit
notifications:
  email:
    - codylee@wellaware.us
